use_frameworks!

platform :ios, '10.0'

target 'UnifiedForumUI_Example' do
  pod 'UnifiedForumUI', :path => '../'

  target 'UnifiedForumUI_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
